-- Race-free dedupe for /api/convert.
--
-- Without a unique index, the previous select-then-insert flow had two problems:
--   1. The dedupe SELECT ran under the anon key, which RLS blocks on
--      conversion_events — every request saw zero existing rows and inserted a
--      duplicate.
--   2. Even with the service role, two near-simultaneous requests with the
--      same (kol_slug, session_id, event_type) would both pass the SELECT and
--      both INSERT.
--
-- This non-partial unique index closes both: the route now upserts with
-- ON CONFLICT (kol_slug, session_id, event_type) DO NOTHING.
--
-- A previous draft used a partial index (WHERE session_id IS NOT NULL), but
-- PostgREST/Supabase `upsert(..., { onConflict: "..." })` only emits the
-- column list — it cannot express a partial-index predicate, so Postgres
-- can't match a partial index as the conflict target and the upsert fails at
-- runtime with "no unique or exclusion constraint matching the ON CONFLICT
-- specification".
--
-- A non-partial index gives the same dedupe behavior because Postgres treats
-- NULLs as distinct in unique indexes by default (NULLS DISTINCT) — multiple
-- rows where session_id IS NULL are still allowed, so anonymous (no-session)
-- events stay un-deduped exactly as before.
CREATE UNIQUE INDEX IF NOT EXISTS conversion_events_dedup_idx
  ON conversion_events (kol_slug, session_id, event_type);
